permalink: /:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
markdown: redcarpet
pygments: true
paginate: 10
title : 
tagline: 

author :
  name : kui2015
  email : wujinkui1991@163.com
  github : kui2015

production_url : http://kui2015.github.io

comments :
  provider : disqus
  disqus :
    short_name : kui2015-blog

