permalink: /:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
markdown: redcarpet
pygments: true
paginate: 10
title : JingWoo
tagline: JingWoo
author :
  name : jingwoo
  email : wujinkui1991@163.com
  github : jingwoo
  twitter : niubods

production_url : http://jingwoo.github.io

comments :
  provider : disqus
  disqus :
    short_name : jingwoo-blog

